### ISSUE TITLE
Missing Icon file?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [fsmosca/Python-Easy-Chess-GUI#28]
On the screenshot in the readme, I noticed that the icon is the tkinter default 'leaf' style icon.  PySimpleGUI has its own built-in icon that is normally shown.

![image](https://user-images.githubusercontent.com/13696193/60208083-6e1b3700-9825-11e9-8b05-106a24f133d9.png)

**Comment by fsmosca** [comment]
Have not yet decided on that icon, I will surely include it in v1.0.

**Comment by fsmosca** [comment]
- [x] Add icon folder.
  - [x] Add pecg.ico
  - [x] Add adviser.ico
  - [x] Add enemy.ico

**Comment by MikeTheWatchGuy** [comment]
For icons, have you considered using a base64 icon?

**Comment by fsmosca** [comment]
Yes I am considering of using base64.
