### ISSUE TITLE
Name change....

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [fsmosca/Python-Easy-Chess-GUI#29]
I would think about a sexier name down the road, or ASAP.  

You've got what may very well be the premier chess program written in Python, certainly the best that has a GUI.

Chess Master
Chess Multi-AI
Multi-AI Chess

I'm TERRIBLE at naming stuff, or am on short notice.  I renamed PySimpleGUI several times.   Had several icons made too.  I went with the best of them.  The point is that marketing counts.

If you can write at all, I would consider writing some articles on it. Get listed in Chess blogs, etc.  I'm serious.  This thing is likely to take off pretty well considering the stuff that it does and that it's such a nice GUI.

Here are a few things I thought of that may make a positive difference in your program's reach / use.  I really would like to see it get a lot of use.  It looks awesome and you've put time into it.  These things may or may not have an impact.  They're things I've learned from the past year of PySimpleGUI.
1. EASILY packaged - has to work every time out of the box.  I was going to update my version when I discovered yours and didn't.  I was going to put all the graphics in the 1 source file.
2. Has an easy recognizable name / memorable
3. Doesn't hurt to have a logo.  They're under $40 on Fiverr.
4. Write an article.  Within a few weeks of releasing PySimpleGUI 1.0 I wrote an article that was published on OpenSource.  It went nuts and was picked up and re-distributed all over.  I'm learning that other people rarely (never) write articles for your software, it's kinda up to you.
5. Reddit has been a good place to get the word out. I'm sure there are tons of chess forums, et
6. Get onto the list of "Python Applications" - I'll look at this one. I found a list of Python applications that look like windows programs. That's what the list is meant to be "Application Software".  It's a rare thing in the Python world.
7. Open yourself up to the AI community.

That last one could be super interesting. I'm wondering if it's possible to be the bolt-on display package or some other aspect of chess oriented AI work.   I dunno, just thinking out loud.

I would like to see your software used.  There is too little examples of Python GUI programs, especially good ones :-)  

Anyway.... just my opinions.  They're free, meaning they're pretty much worthless 😁

**Comment by fsmosca** [comment]
I actually thought about changing the program name, but finding a good and unique name is not easy. I remember naming my command line chess game analyzer, it is called Chess Artist. Some people liked it. I will try to start looking for a new name for this chess GUI.

Thanks for your pointers, will take a note on those. BTW I read and post at http://talkchess.com/forum3/index.php. Look for member named Ferdy.

**Comment by MikeTheWatchGuy** [comment]
It's not easy, but it's worth the effort.  MANY packages are out there that are well done.  They work.  People spent tons of time on it, but they go nowhere.  They sit with no one finding out about it.  Name is a part of that.

If you listen to any of the Python podcasts, they give this very same advice to people wanting to publish their first package.  That engineers typically hate doing marketing and sales crap, but it's almost a must to do if you want to seriously be found.  

It sounds like you've already got some great outlets, forums and the like.

It took me a YEAR to figure out the name of this new patent I'm working on.  A full year.  I tried all kinds of names, bought lots of URLs and then finally one came to me one day, like a bolt of lightening, and it was obvious that it should be the name.

Let it keep cooking in your subconscious... you'll find something.
