### ISSUE TITLE
[Enhancement]  Right click menu

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [fsmosca/Python-Easy-Chess-GUI#30]
Do you know about the right click menu that is available to all elements?

I don't now exactly what action you would add to say a piece on the board, but it could be super useful.  Maybe "Remove Piece" or "Quit" or ???

Anyway, just a reminder that it's a tool in your arsenal.

Same with ToolTips.  

These kinds of tools have turned out to be super useful at times.

# The debugger

FINALLY, it's not documented well, but if you're running plain PySimpleGUI, then you can press the BREAK key or CONTROL+BREAK key to bring up the debugger.  This feature is so amazing because it allows you to debug your code while it continued to run.... and it's after you started running the program, perhaps without an IDE.

So, you're running your program by double clicking on it but after a while there's a bug that starts showing up intermittently.   With this debugger you can do almost anything because there's a REPL built in.  With that you can literally execute code.

The reason I thought of it is the right click menu.  On the popup window that shows up in the corner after pressing BREAK, you can right click any text and you'll get a right click menu to - Run main debugger (open the other debug window) or Exit.

**Comment by fsmosca** [comment]
I saw the right click menus in the documentation, but have not explored it yet. I have tried the debugger, I can see variable values, I don't know how to use the items in REPL & Watches.

My debugging method is only placing print() in my code. When program encountered an error, I look on the error messages and traceback. My IDE is Spyder on Anaconda.

**Comment by MikeTheWatchGuy** [comment]
By far the best way to debug is using your IDE, whether that be PyCharm or Spyder.

The built-in debugger is excellent for situations where
1. You've started your program in your IDE, but not in a way that you can debug it.
2. You started your program from the command line
3. You double clicked to start the program
4. You didn't put a print at the point in the program that has the problem
5. You don't know for sure where your program is getting the libraries

Basically it gives you the ability to find problems when all of your normal tools are not available

This is the better of the Windows to be looking at for hands-on debugging using the debugger.  BTW, the debugger is better documented in the package documentation for the debugger itself.   [`imwatchingyou`](https://github.com/PySimpleGUI/imwatchingyou) is the debugger package that the built-in debugger is based on.

![image](https://user-images.githubusercontent.com/13696193/60388987-c5b8dd00-9a87-11e9-84fb-49a28061a250.png)

As you can see, there's a `REPL` prompt where you can examine variables, type in code, etc.  There are also 3 "watches" That you can setup on this page.  These can be any expression you want, not just limited to variable names.

I mentioned it being good for debugging where your packages are being pulled in from.

To find where your PySimpleGUI is coming from, just type `sg` into the REPL>>> prompt.  You already did an `import PySimpleGUI as sg` previously in your code.  

You can use the same kind of technique to get the tkinter version.  I can't recall how the code imported tkinter, so I typed in a new `import` command.

Here is a screenshot of collecting all of that information:

![image](https://user-images.githubusercontent.com/13696193/60389029-5bed0300-9a88-11e9-8bf8-faa47ebe17c3.png)


The other tab in this window brings you to the "Variables" portion of the debugger.  Here you can watch your variables change in real time.  You can explore a big.  Anywhere you in the debugger where you can enter a variable, you can also enter an expression.  


In summary, this is a tool that I don't actively use to debug my programs like I would with an IDE.  I use PyCharm for that level of debugging.   I use the built-in debugger for situations where I don't have an IDE connected to the running program,.  It's also really good for giving instructions to people to collect data for me in the process of debugging their problems.

This debugger is one of the new things about to be documented in the new readme.
