### ISSUE TITLE
GUI crashes when playing en passant.

### ISSUE THREAD

**Issue by Davpouck** [fsmosca/Python-Easy-Chess-GUI#38]
fix: 
- [line 2057](https://github.com/fsmosca/Python-Easy-Chess-GUI/blob/541f920be0b96ce6d5961fa17db0e28f0afaad18/python_easy_chess_gui.py#L2057): add `window,`
- same for [line 2280](https://github.com/fsmosca/Python-Easy-Chess-GUI/blob/541f920be0b96ce6d5961fa17db0e28f0afaad18/python_easy_chess_gui.py#L2280)

**Comment by fsmosca** [comment]
Thanks I will fix it.

**Comment by fsmosca** [comment]
Fix in https://github.com/fsmosca/Python-Easy-Chess-GUI/commit/c6e7bd73ef68f6cc6e4b3c6a97f8c802fd713bfe
