### ISSUE TITLE
error : bad attribute "-disabled"

### ISSUE THREAD

**Issue by tissatussa** [fsmosca/Python-Easy-Chess-GUI#41]
i think i encounter a serious bug : bad attribute "-disabled" .. the following error lines occur after starting the application (which seems OK) at all menu actions, eg. at "User / Set name" and "Engine / Manage / Install" :
```
$ python3 python_easy_chess_gui.py
Traceback (most recent call last):
  File "python_easy_chess_gui.py", line 3578, in <module>
    main()
  File "python_easy_chess_gui.py", line 3574, in main
    pecg.main_loop()
  File "python_easy_chess_gui.py", line 2829, in main_loop
    window.Disable()
  File "/home/roelof/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py", line 9239, in disable
    self.TKroot.attributes('-disabled', 1)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1976, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: bad attribute "-disabled": must be -alpha, -topmost, -zoomed, -fullscreen, or -type
```

maybe i can provide more info to solve this issue .. I use Xubuntu 20.04 and i'm not a beginner at Linux .. do i miss some module on my OS ?  Can i supply some log ?

**Comment by fsmosca** [comment]
This issue is the same in #36 and #37.

This issue is from the module PySimpleGUI where this GUI depends. By the way what PySimpleGUI version do you use.

This is the hack or temporary fix to resolve the issue. Modify the pysimplegui.py source with the following. But perhaps the new pysimplegui version would already solve this. I have not tried the latest one.
```python
    def disable(self):
        """
        Disables window from taking any input from the user
        """
        if not self._is_window_created():
            return
        self.TKroot.grab_release()  # Only 'disables' an already 'enabled' window. Does nothing to a normal window
        # self.TKroot.attributes('-disabled', 1)
        # self.TKroot.grab_set_global()

    def enable(self):
        """
        Re-enables window to take user input after having it be Disabled previously
        """
        if not self._is_window_created():
            return
        self.TKroot.grab_set  # I read grab_set_global messes with all open windows so I wanted to avoid that
        # self.TKroot.attributes('-disabled', 0)
        # self.TKroot.grab_release()
```

This works on windows 10, and linux, perhaps it will work too in osx.

I also make a comment regarding this at https://github.com/PySimpleGUI/PySimpleGUI/issues/1538

**Comment by tissatussa** [comment]
thank you !
I changed the code in PySimpleGUI.py accordingly and it seems to work !
btw. I have the latest PySimpleGUI version 4.45.0 !?

**Comment by fsmosca** [comment]
Thanks for info. So the latest 4.45.0 still does not work, and that temporary fix is working.
The man from PySimpleGUI is busy, there are a lot of issues so far on his excellent framework, probably there are other priorities.
