### ISSUE TITLE
ModuleNotFoundError: No module named 'chess.uci'

### ISSUE THREAD

**Issue by janroks** [fsmosca/Python-Easy-Chess-GUI#43]
I have done the "py -m pip install chess", and been told that it went fine, but still get the message 

ModuleNotFoundError: No module named 'chess.uci'

Anyone have the same problem? Or am I doing something wrong?

**Comment by fsmosca** [comment]
Open your console then type the following, lets see if python chess is detected.

```
python --version
python
import chess
chess.__version__
```

**Comment by janroks** [comment]
Hi

Thanks for the advice. When I type
import chess
chess.__version__

in console, it says '1.7.0', so it seems it's detected.

When I type py --version in terminal (windows), it says 3.9.1.




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by fsmosca** [comment]
This is strange, the current source code has no `chess.uci`.

I tried the following in windows 10 with powershell and it worked.
```
git clone https://github.com/fsmosca/Python-Easy-Chess-GUI.git
pip install chess
pip install pyperclip
pip install pysimplegui
```
