### ISSUE TITLE
Best Move display when I use stockfish

### ISSUE THREAD

**Issue by lukillo369** [fsmosca/Python-Easy-Chess-GUI#47]
First, I love that you have put this out to the public for people to use.
I am trying to make a robot that uses the stockfish engine to play along with the game in real-time with a board. 
Would there be a way I can gather the stockfish best move data and then send that to the robot for it to move?
Any help would be great, even if you send me on my way with only a little help.
The robot I am using is Niryo One.

**Comment by fsmosca** [comment]
I am not familiar with a robot playing chess that uses an engine. Somehow you need the **robot manual** how to connect it to an external device or program. 

But [buzzCraft](https://github.com/buzzCraft) has demonstrated using a robot from this [video](https://www.youtube.com/watch?v=svgM8sdBHIU) using this UI. Perhaps you can contact him.
